### ISSUE TITLE
Are you still maintaining this?

### ISSUE THREAD

**Issue by tobidelius** [evanleck/sinatra-strong-params#1]
Some tests might be useful as well ? :)

**Comment by evanleck** [comment]
I sure am! If I get time to, I'll work on adding some tests but I'm always happy to check out a pull request if you'd like to put something simple together.

Cheers!

**Comment by shadowbq** [comment]
+1 tests

**Comment by gustavosobral** [comment]
I think this one can be closed? The answer is yes.

**Comment by evanleck** [comment]
Yep!
