### ISSUE TITLE
Publish version 0.1.0

### ISSUE THREAD

**Issue by gustavosobral** [evanleck/sinatra-strong-params#13]
Hi @evanleck,

I bumped the gem version here from 0.0.3 to 0.1.0 but on RubyGems the latest version still 0.0.3. Do I need to do something else to publish the release?

Thanks

**Comment by evanleck** [comment]
Yeah, publishing a gem requires an account at rubygems.org and ownership of the gem there (I think). I just released 0.1.0 there so you should see it now.

**Comment by gustavosobral** [comment]
Great, I could update the gem in a project that I'm using it. Thanks
