### ISSUE TITLE
use of .blank? on Hash is an ActiveSupport idiom

### ISSUE THREAD

**Issue by shadowbq** [evanleck/sinatra-strong-params#2]
**use of .blank? on Hash is an `ActiveSupport` idiom**

``` debug
lib/sinatra/strong-params.rb@line21   unless @params.blank?
```

Fix it (replace it with `.empty?`) 

**NOTE: Hash implements .blank? as an alias to .empty?** 

or add it in your Gemfile add

``` ruby
gem 'active_support'
```

Within the the `/lib/sinatra/strong-params.rb`

``` ruby
require 'active_support/core_ext/object/blank'
```

**Comment by evanleck** [comment]
Merged with pull request https://github.com/evanleck/sinatra-strong-params/pull/3
