### ISSUE TITLE
Not having to pass the same key twice in needs and allows

### ISSUE THREAD

**Issue by gustavosobral** [evanleck/sinatra-strong-params#7]
Hi,

I think having to pass the same key twice when using `needs` and `allows` is confusing and cause a lot of duplication. As I see it, If a param is needed, it is being allowed already.

Like just: 
`get '/search', needs: [:q], allows: [:start_datetime] do`

Instead of: 
`get '/search', needs: [:q], allows: [:q, :start_datetime] do`

This is a suggestion/discussion, what do you think? I can come up with something if you think this make sense.

Cheers for the gem!

**Comment by evanleck** [comment]
Makes sense to me, there's no reason that a parameter should be required but not allowed. Would you like to create a pull request with those changes?

**Comment by gustavosobral** [comment]
Great. Yes, I will try to come up with something
